### ISSUE TITLE
React version on peer dependencies is 16.6.0

### ISSUE THREAD

**Issue by lemol** [xnimorz/use-debounce#1]
Is this intentional or it have to be "^16.7.0-alpha.0"?

https://github.com/xnimorz/use-debounce/blob/13c5d23b198378e6c3a80bd554cce54e62be5956/package.json#L25

**Comment by xnimorz** [comment]
Hello, @lemol 
Thank you for the issue.
Yes, it has to be "^16.7.0-alpha.0", because react hooks are defined only in this version.
I'll fix it a bit later.
