### ISSUE TITLE
Add a "cancel" method to the callback

### ISSUE THREAD

**Issue by eliseumds** [xnimorz/use-debounce#10]

**Comment by xnimorz** [comment]
Thanks for suggestion @eliseumds ! I think I'll add it with https://github.com/xnimorz/use-debounce/issues/5 

You are welcome to PR :)

**Comment by thibaultboursier** [comment]
Hi @xnimorz,

I'm working on adding a cancel method. I'll make a pull request soon.

**Comment by xnimorz** [comment]
Hello @eliseumds 

I've cut the 1.0.0 release. 
Now you can use:
```
yarn add use-debounce@1.0.0
```

The example with `cancel` callback is here: https://codesandbox.io/s/4wvmp1xlw4

Thanks for @thibaultboursier for contributing
