### ISSUE TITLE
useDebouncedCallback() has a slightly wrong type

### ISSUE THREAD

**Issue by VanTanev** [xnimorz/use-debounce#103]
```typescript
export interface DebouncedState<T extends (...args: any[]) => ReturnType<T>> extends ControlFunctions {
  (...args: Parameters<T>): ReturnType<T>;
}
```

Should instead be:
```typescript
export interface DebouncedState<T extends (...args: any[]) => ReturnType<T>> extends ControlFunctions {
  (...args: Parameters<T>): ReturnType<T> | undefined;
}
```

The reason is that unless we're invoking on leading edge, the `result` ref will not be set until the function has been debounced at least once.

Reproduction: https://codesandbox.io/s/use-debounced-callback-return-type-57jme

**Comment by xnimorz** [comment]
Thank you, @VanTanev for spotting this!
I'll fix it soon

**Comment by xnimorz** [comment]
Published in v.6.0.1 Thanks for reporting!
