### ISSUE TITLE
Bad example for useDebouncedCallback in README

### ISSUE THREAD

**Issue by TonisPiip** [xnimorz/use-debounce#105]
in the readme example of useDebouncedCallback you have:
```
 const debounced = useDebouncedCallback(
    // function
    (value) => {
      setValue(value);
    },
    // delay in ms
    1000
  );
```

But it's returning an array, so it really should be 

`const [debounced] = useDebouncedCallback(`

**Comment by xnimorz** [comment]
Hi @TonisPiip 
`useDebouncedCallback` returns an object. You can check the example here: https://codesandbox.io/s/x0jvqrwyq 

So the Readme shows the right information.

**Comment by abologna-rigup** [comment]
I am on the latest release and @TonisPiip is right. I was able to get the function only as an array. Attaching screenshot:

![image](https://user-images.githubusercontent.com/66850129/114056106-f336db00-9856-11eb-83a3-f6a29dd69cbc.png)

**Comment by xnimorz** [comment]
It looks pretty odd, as this is an API from the old major versions. 

I checked it by installing the latest version `6.0.1`: 
![image](https://user-images.githubusercontent.com/1178825/114109444-f32dee00-98dd-11eb-9bc6-299c6ad64530.png)

Can you check the version in `node_modules/use-debounce/package.json` and the content inside .d.ts files in `node_modules/use-debounce/esm/useDebouncedCallback.d.ts` and `node_modules/use-debounce/lib/useDebouncedCallback.d.ts`? 

This information should help me to understand your issue

**Comment by TonisPiip** [comment]
I have `"use-debounce": "3.4.2"` So yes, it's an older version.  

Perhaps the npm release version isn't same as master branch?

**Comment by xnimorz** [comment]
The last version according to the npm is https://www.npmjs.com/package/use-debounce 
Master branch represents usually the latest version in this repo.

**Comment by xnimorz** [comment]
Feel free to reopen this issue if you still have any problems.

**Comment by robertu7** [comment]
I'm using `6.0.1` and having the same issue as @TonisPiip, the TypeScript definition is fine but the actual code is returning an array.
