### ISSUE TITLE
How do you mock useDebounce? 

### ISSUE THREAD

**Issue by DoryZi** [xnimorz/use-debounce#109]
All Mocking attempts create errors:
`import useDebounce from 'use-debounce'`
`jest.mock('use-debounce')`

``` TypeError: (0 , _useDebounce.useDebounce) is not a function or its return value is not iterable ```
trying to target just that mock also fails:

```
jest.mock('use-debounce',() => {
  return {
    useDebounce: jest.fn(value => [value])
  }
})
```

also gives the same error.
using mock timer didn't work either.

**Comment by xnimorz** [comment]
Hi @DoryZi 
Thanks for the question!

Could you provide a small repo with a problem to help me find out what is your case? 

In general, it could be mocked by simple `jest.mock`. I've prepared a small repo with a simple mocking: https://codesandbox.io/s/eloquent-bassi-hpmct?file=/src/app.spec.js 
However, codesandbox doesn't support `jest.mock` as well as the rest jest functions like `useFakeTimers`, so you can download the repo and then run `yarn; yarn test` to check how it works:
![image](https://user-images.githubusercontent.com/1178825/118046954-be9cce80-b382-11eb-9476-b5cbcc810a98.png)

![image](https://user-images.githubusercontent.com/1178825/118047063-e2f8ab00-b382-11eb-8ad7-d6e02601fdce.png)


(the issue with codesandbox: https://github.com/codesandbox/codesandbox-client/issues/513)

**Comment by DoryZi** [comment]
try this?
https://codesandbox.io/s/hardcore-leftpad-86o8n?file=/src/app.spec.js

**Comment by DoryZi** [comment]
TRy looking at it now.

**Comment by xnimorz** [comment]
jest.mock works good for this example too. 
```
jest.mock("use-debounce", () => {
  return {
    useDebounce: () => {}, // your mock
    useDebouncedCallback: () => {} // your mock,
  };
});
```

**Comment by xnimorz** [comment]
I'm closing this issue for now. If you still have problems, please send me a small repro with the problem, I'll check it.
