### ISSUE TITLE
` useDebouncedCallback` does not have ` equalityFn` option in the type definition.

### ISSUE THREAD

**Issue by harrisonywu** [xnimorz/use-debounce#119]
**Describe the bug**
`useDebouncedCallback` does not have `equalityFn` option defined in the type definition. 

In documentation, it says both `useDebounce` and `useDebouncedCallback` have `equalityFn` provided.
![image](https://user-images.githubusercontent.com/16639666/131380667-d8f07cbf-d7f2-4ad4-8bd5-58b2ffb1ccc9.png)

Looking at the Type definition, and `Options` does not have `equalityFn` defined.
![image](https://user-images.githubusercontent.com/16639666/131381206-af73ffa1-f73d-440e-9cc7-3acef6e75530.png)

Admittedly, I haven't looked into src code to see if `equalityFn` logic is actually available to `useDebouncedCallback`, but if it is, then this is simply a type definition issue. From documentation, it seems like both `useDebounce` and `useDebouncedCallback` share options, so they should also share a type, which they currently are not.

I may come back to investigate/resolve this in a bit, but busy with some other things right now.

**use-debounce version: 7.0.0**

**Comment by xnimorz** [comment]
Hey @harrisonywu  sorry for the long response. 
`equalityFn` is not presented in useDebouncedCallback, because there are no values to compare.
I'll mark that this function is a specific for the useDebounce

**Comment by xnimorz** [comment]
https://github.com/xnimorz/use-debounce/blob/master/README.md#options
