### ISSUE TITLE
"leading: true" not working for v7

### ISSUE THREAD

**Issue by mntnoe** [xnimorz/use-debounce#124]
**Describe the bug**
For the versions 7.0.0 and 7.0.1, setting `{ leading: true }` does not trigger an immediate change in `useDebounce`. It works in 6.0.1 and below.

**To Reproduce**
- The sandbox example linked to in the readme file (https://codesandbox.io/s/rr40wnropq) uses `use-debounce@6.0.0-beta`. Add the option `{ leading: true }` and observe that the debounced value is updated immedately for the first change.
- Change the version number to 7.0.0 or 7.0.1, and observe that the behavior is now as if `{ leading: true }` is not given.

**Expected behavior**
Setting `{ leading: true }` should trigger immediately for the first change, and subsequently trigger immediately on changes after the `wait` timeout has expired.

**use-debounce version:**
7.0.0 and 7.0.1

**Comment by xnimorz** [comment]
Hey, thank you for reporting the issue. 
You're welcome to open the PR to fix it!

**Comment by xnimorz** [comment]
Labelling it as a good for new contributors, who are looking for possibilities to start with open source

**Comment by xnimorz** [comment]
Hey @mntnoe 
I've published v8.0.0 of the library.

Now it works with `leading: true` correctly, here is the demo:

https://codesandbox.io/s/cache-example-with-areas-and-leading-param-119r3i

If you get any issues during the update from 7.x.x => 8.x.x here is a guidance: https://github.com/xnimorz/use-debounce/blob/master/CHANGELOG.md#800

**Comment by xnimorz** [comment]
I'm closing this issue as it should be resolved for now. Please, feel free to re-open it if you still get any issues with it

**Comment by mntnoe** [comment]
Thank you for looking into this. When using `{ leading: true }`, we get some strange behavior in our code with v8.0.0, where the new value is used initially, but then reverted:

```
VALUE  DEBOUNCED
a      a
b      a
b      b
bb     a
bbb    a
bbbb   bbbb
```

I'll try to investigate what happens when I get time.

**Comment by xnimorz** [comment]
@mntnoe interesting, thanks, I'll try to reproduce it too.

**Comment by xnimorz** [comment]
I cannot repro it now. If you have an example, please share it. I'll close the issue for now

**Comment by rostero1** [comment]
Here's an example where it doesn't seem to be working for v8 or v9:  https://codesandbox.io/s/bold-hooks-s503vs?file=/src/App.js
