### ISSUE TITLE
useDebouncedCallback gives incorrect import suggestion in VSCode

### ISSUE THREAD

**Issue by c-ehrlich** [xnimorz/use-debounce#131]
**Describe the bug**
When using AutoComplete in VS Code for `useDebouncedCallback`, it suggest importing it from `use-debounce/lib`. However this import doesn't work, the correct input is `use-debounce`

**To Reproduce**
Install use-debounce, create a React component,  type `const a = useDebouncedCallback`, and look at the autocomplete suggestions for the import

**Expected behavior**
It should suggest to import from `use-debounce`

**use-debounce version:**
7.0.1

**Comment by xnimorz** [comment]
Hey @c-ehrlich 
Thanks for reporting!

I've published v8.0.0 of the library. 

Now it resolves pathes correctly:
![image](https://user-images.githubusercontent.com/1178825/166165231-6d118f46-4240-434b-9754-3090f085c18d.png)

If you get any issues during the update from 7.x.x => 8.x.x here is a guidance: https://github.com/xnimorz/use-debounce/blob/master/CHANGELOG.md#800

**Comment by xnimorz** [comment]
I'm closing this issue as it should be resolved for now. Please, feel free to re-open it if you still get any issues with it
