### ISSUE TITLE
Callback doesn't fire if component unmounts before delay elapses

### ISSUE THREAD

**Issue by gragland** [xnimorz/use-debounce#14]
I'm using `useDebouncedCallback` and noticed that if the component unmounts (such as an edit window that is closed) before the delay finishes the callback never fires. This makes sense, as you wouldn't want a callback to set state in a component that has already unmounted. But it would be nice if there was some way for me to trigger the callback manually if it hasn't fired yet. Maybe a `callPending` function in addition to `cancel`? I'd then be able to call that function when the user takes an action that would cause the component to unmount.

**Comment by xnimorz** [comment]
Hello, @gragland !
I agree with you, such feature could be handy for some situations. 
I'll add it with 1-2 days, and will write here when I publish the release.

**Comment by xnimorz** [comment]
I've just published use-debounce@1.1.1 with `callPending` support. 
Here you can find examples https://github.com/xnimorz/use-debounce/blob/master/test/callback.test.js#L196-L293 

And short docs: https://github.com/xnimorz/use-debounce#callpending-method

Thank you again for the idea!

**Comment by gragland** [comment]
@xnimorz Thanks!

**Comment by guillaume86** [comment]
Hi, great job on this hook.

I think this use case seems common enough to justify a dedicated option, something like "callPendingOnUnmount: boolean". 

It's not a big issue as it's easy enough to add user side but it would be a nice thing to have.
More importantly it would also make it clear from the docs of that option that by default a pending call is NOT done on unmount (which can lead to hard to debug issues).

**Comment by xnimorz** [comment]
Hello @guillaume86 
It's more like a definite user case, which users can make on their own.
