### ISSUE TITLE
use-debounce to auto-save multi input form

### ISSUE THREAD

**Issue by WebDev-Akhil** [xnimorz/use-debounce#142]
I'm trying to create an auto-save form. Whenever a user types something in the multi-field form, a function should run to submit the form data. From the readme examples, I understand how to do it for a single form field input but I would like to do it for multiple form fields (useState({object})

Codesandbox: https://codesandbox.io/s/cache-forked-ncz0tf?file=/src/index.js

Code:

in the below example, I want to run the submitForm function for every debounced value, so it creates auto-save effect

```js
import React, { useState } from "react";
import ReactDOM from "react-dom";
import { useDebounce } from "use-debounce";

function Input() {
  const [profile, setProfile] = useState({
    name: "John",
    lastName: "Doe"
  });
  const [d] = useDebounce(profile, 1000);

  const handleChange = (x, value) => {
    setProfile({ ...profile, [x]: value });
  };

  const submitForm = (event) => {
    //API PUT request
  };

  return (
    <div>
      <input
        type="text"
        name="name"
        id="full-name"
        onChange={(e) => {
          handleChange(e.target.name, e.target.value);
        }}
        value={profile.name}
      />
      <input
        type="text"
        name="lastName"
        id="full-name"
        onChange={(e) => {
          handleChange(e.target.name, e.target.value);
        }}
        value={profile.lastName}
      />
      <button type="submit" onClick={submitForm}>
        Save
      </button>
      <p>
        Actual value: {profile.name} {profile.lastName}
      </p>
      <p>
        Debounced value: {d.name} {d.lastName}
      </p>
    </div>
  );
}
```

**Comment by xnimorz** [comment]
Hey @WebDev-Akhil, 
Answering your question of how to make denounced changes in case several nested components, I'd suggest going with lifting the state up. So, the component, in the end, would call some provided function to change the state from the component higher. You can follow this technic here:
https://reactjs.org/docs/lifting-state-up.html
