### ISSUE TITLE
[9.0.1] TS7016: Could not find a declaration file for module 'use-debounce'.

### ISSUE THREAD

**Issue by efstathiosntonas** [xnimorz/use-debounce#152]
**Describe the bug**
After upgrading to `9.0.1` the types are broken. 

`TS7016: Could not find a declaration file for module 'use-debounce'.`

**To Reproduce**
Upgrade to `9.0.1` on a typescript project

**use-debounce version:**
`9.0.1`

**Comment by sven-meyer-wetter-com** [comment]
Same problem here...

**Comment by grzegorz-zadora** [comment]
Same here

**Comment by xnimorz** [comment]
Hey all!
Sorry for inconvenience. I’ll fix it within a day. 
for now please use 8.0.4

**Comment by efstathiosntonas** [comment]
@xnimorz I think it's broken on react-native too, it throws this:

```Error: While trying to resolve module `use-debounce` from file `/Users/stathis/WebstormProjects/src/xxxx.tsx`, the package `/Users/stathis/WebstormProjects/xxxxxx/node_modules/use-debounce/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/stathis/WebstormProjects/xxxxx/node_modules/use-debounce/dist/index.cjs`. Indeed, none of these files exist:```

**Comment by xnimorz** [comment]
Okay, So I've reverted recent 9.0.0 changes, and it should be back to normal.

You can use 9.0.2, it should work fine

**Comment by grzegorz-zadora** [comment]
`9.0.2` works brilliantly!

@xnimorz Thank you very much! :bow:

**Comment by davidkarlsson** [comment]
I still get this issue with 9.0.3 in combination with TypeScript 5.0.2 and `nodeResolution` set to the new `bundler` option:

```
Content/Test.tsx:5:38 - error TS7016: Could not find a declaration file for module 'use-debounce'. 'D:/Test/.yarn/__virtual__/use-debounce-virtual-e226286c71/0/cache/use-debounce-npm-9.0.3-87fc1a9d59-e9aa3b89ab.zip/node_modules/use-debounce/dist/index.module.js' implicitly has an 'any' type.
  There are types at 'D:/Test/.yarn/__virtual__/use-debounce-virtual-e226286c71/0/cache/use-debounce-npm-9.0.3-87fc1a9d59-e9aa3b89ab.zip/node_modules/use-debounce/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'use-debounce' library may need to update its package.json or typings.

5 import { useDebouncedCallback } from 'use-debounce';
```

**Comment by fregante** [comment]
Updating to 9.0.4 fixes the issue. It worked for me on `nodeResolution: bundler`
