### ISSUE TITLE
Link to dan_abramov's tweet is a dead link now

### ISSUE THREAD

**Issue by kamui** [xnimorz/use-debounce#179]
**Describe the bug**
This [tweet](https://github.com/xnimorz/use-debounce/blob/master/README.md?plain=1#L70) reference in the README is now a dead link, so that section of the intro is missing a bit of context when it goes into explaining the bit of code.

**To Reproduce**
Go to the README of this repo

**Expected behavior**
If the tweet no longer exists anywhere,, explain the contents of the tweet or what the insight is in the README.

**Comment by xnimorz** [comment]
Fixed in https://github.com/xnimorz/use-debounce/pull/180
