### ISSUE TITLE
Dependency Conflict with React 19.0.0-rc When Installing use-debounce

### ISSUE THREAD

**Issue by shockValue666** [xnimorz/use-debounce#181]
**Describe the bug**
When trying to install the use-debounce package in a project using React 19.0.0-rc (npx create-next-app@latest), I encounter a dependency conflict error. The error indicates that use-debounce requires react@>=16.8.0, but it fails to resolve with the current version of React in my project.

**To Reproduce**
	1.	Create a new Next.js project (npx create-next-app@latest).
	2.	Attempt to install use-debounce (npm install use-debounce).
	3.	Observe the dependency conflict error.

**Expected behavior**
use-debounce should either resolve correctly with React 19.0.0-rc, or there should be a clear indication that this version of React is not supported.

**use-debounce version:**
10.0.2

**Comment by xnimorz** [comment]
Hey @shockValue666 . 
I believe by default, next-app is served with `react: ^18` notation and as such, to install `react@rc` you should switch to rc of next.js as well. 

Unfortunately, NPM is built in a way, they cannot resolve rc / beta versions correctly https://stackoverflow.com/questions/67934358/npm-including-all-range-of-pre-release-when-defining-peer-dependency

As such, I'm removing peerDependency from `use-debounce@10.0.3`. Should be available now
