### ISSUE TITLE
useDebouncedCallback Doesn't appear to have the equalityFn anymore?

### ISSUE THREAD

**Issue by CMarshall92** [xnimorz/use-debounce#187]
**Describe the bug**
I was updating some code I have in typescript and noticed that the equalityFn on the options passed into the third argument of useDebouncedCallback doesn't appear to exist any more, was there a reason for this remove and can we replicate behaviour any other way?

**To Reproduce**
Install use-debouse@4.0.0 and try 

```js
import isEqual from 'lodash.isequal'

 const [_, _, _] = useDebouncedCallback(
    (values) => {},
    autoSaveAfter,
    { maxWait: forceAutoSaveAfter, equalityFn: isEqual }
  )
 ```

**Expected behavior**
equalityFn to be present in the options

**use-debounce version: 4.0.0*

**Comment by CMarshall92** [comment]
So for a bit more context my code looks a bit like this so i was under the impression i had to use the callback debouncer?

```js
const [autoSaveDebounce, _, autoSaveDebounceCallPending] = useDebounce(
    (values: any) => {
      const { isSubmitting } = formState

      if (!isSubmitting && !submitted && status !== SAVESTATUS.SAVE_IN_PROGRESS) {
        setAutoSaveStatus(SAVESTATUS.SAVE_IN_PROGRESS)
        handleAutoSave(values)
          .then(() => {
            setAutoSaveStatus(SAVESTATUS.SAVED)
          })
          .catch((err: any) => {
            setAutoSaveStatus(SAVESTATUS.SAVE_ERROR)
            throw err
          })
      }
    },
    autoSaveAfter,
    { maxWait: forceAutoSaveAfter, equalityFn: isEqual }
  )
```

Basically i have a callback that i want to call that will do a network request when its called

**Comment by xnimorz** [comment]
You can check changelog: https://github.com/xnimorz/use-debounce/blob/master/CHANGELOG.md
We never had `equalityFn` for `useDebouncedCallback`. 

So, I'd suggest:
1) Use `useDebouncedCallback` instead of `useDebounce`, as `useDebounce` debounces the value, and your function is treated here as a value. 
2) The function, that you pass to `useDebouncedCallback` should perform arguments check on its own. 

As the result you would have something similar to:
```
const argsCached = useRef();
const [autoSaveDebounce, _, autoSaveDebounceCallPending] = useDebounce(
    (values: any) => {
      const { isSubmitting } = formState

     if (isEqual(argsCached.current, values)) {return;}

      if (!isSubmitting && !submitted && status !== SAVESTATUS.SAVE_IN_PROGRESS) {
        setAutoSaveStatus(SAVESTATUS.SAVE_IN_PROGRESS)
        handleAutoSave(values)
          .then(() => {
            setAutoSaveStatus(SAVESTATUS.SAVED)
          })
          .catch((err: any) => {
            setAutoSaveStatus(SAVESTATUS.SAVE_ERROR)
            throw err
          })
      }
    },
    autoSaveAfter,
    { maxWait: forceAutoSaveAfter,}
  )
```
