### ISSUE TITLE
How to know if the value is debouncing?

### ISSUE THREAD

**Issue by janhesters** [xnimorz/use-debounce#19]
I filter a very large list and use the `useDebounce` hook to delay the entry of the `searchValue`:

```js
const [value, setValue] = useState('');

const [debouncedSearchValue] = useDebounce(value, 500);
useEffect(() => {
  setSearchValue(debouncedSearchValue);
}, [debouncedSearchValue]);
```

I would love to show a `filtering...` message or something like that during the debounce. Is there a way to know whether `useDebounce` is still debouncing?

**Comment by xnimorz** [comment]
Hello, @janhesters 

You can get this info by checking if `debouncedSearcValue` is equal to `value`.

I made an example with 2 cases when you have to filter a large list synchronously and asynchronously:

https://codesandbox.io/s/j2n7n0635y

**Comment by janhesters** [comment]
@xnimorz Wow, thank you so much!
