### ISSUE TITLE
React DOM peer dependency? 

### ISSUE THREAD

**Issue by nickbreaton** [xnimorz/use-debounce#20]
Just installed this hook in my React Native project and got an unsatisfied peer dependency warning for `react-dom`. Looking through the code it doesn't seem like `react-dom` is used anywhere expect the tests. 

Would you mind if I submitted a PR to move `react-dom` to a dev dependency instead of a peer dependency?

Thanks for creating this! 😄

**Comment by xnimorz** [comment]
Hello, @nickbreaton !

Yes, this library should depend only on react. I'll remove react-dom from peerDependency. Will write here when I publish the release.

Thank you!

**Comment by xnimorz** [comment]
I've just published 1.1.3 version where react-dom peer-dependency is removed.

**Comment by nickbreaton** [comment]
Sweet. Thanks @xnimorz!
