### ISSUE TITLE
Types aren't recoginzed

### ISSUE THREAD

**Issue by nmussy** [xnimorz/use-debounce#30]
My IDE isn't picking up the TypeScript definitions.

Adding the following line to the `package.json` fixes the issue:
```json
"types": "./lib"
```

I can make a quick PR if you would like. 👍

Thanks for the great little hook!

**Comment by xnimorz** [comment]
Thank you for the issue!

I will appreciate if you make a PR for it.

**Comment by xnimorz** [comment]
Published `use-debounce@2.2.1`
