### ISSUE TITLE
Missing ESM build

### ISSUE THREAD

**Issue by FredyC** [xnimorz/use-debounce#37]
Hey, just want to point out you are referring to `esm/index.js` in `package.json`, but there is no such build. Perhaps consider a tool like TSDX which takes care of such burden.

https://unpkg.com/browse/use-debounce@3.0.0/

**Comment by xnimorz** [comment]
Thank you, for the information! When I return from the vacations, I’ll fix this and publish new version :) It will be within 3-4 days

**Comment by xnimorz** [comment]
Hello @FredyC !
I've just released `use-debounce@3.0.1` which ships `esm` directory.   https://unpkg.com/browse/use-debounce@3.0.1/

**Comment by FredyC** [comment]
Awesome. Thanks for the package btw, I saw that Dan basically code reviewed a whole thing so there is certainly some quality :) I had some attempts before, but there were issues I wasn't able to figure out.
