### ISSUE TITLE
How to use debounce for EventListeners?

### ISSUE THREAD

**Issue by rtvv** [xnimorz/use-debounce#4]
Example:

```
const windowSizes = useDebounce(window.pageYOffset, 1000)
  const handleScroll = event => {
    //how to debounse windowSizes change?
  }


  useEffect(() => {
    window.addEventListener('scroll', handleScroll)

    return () => {
      window.removeEventListener('scroll', handleScroll)
    }
  }, [])
```

**Comment by xnimorz** [comment]
Hello, @rtvv! Thank you for your question.

At the moment useDebounce allows you to debounce some values, that already stored in your state. 

I wrote an example to show how you can debounce the pageYOffset parameter. You can try it here: https://codesandbox.io/s/10jk10r0m7

```
import React, { useState, useEffect } from "react";
import ReactDOM from "react-dom";
import { useDebounce } from "use-debounce";

function Input() {
  const [currentPosition, setPosition] = useState(window.pageYOffset);
  const debouncedPosition = useDebounce(currentPosition, 300);

  const handleScroll = event => {
    setPosition(window.pageYOffset);
  };

  useEffect(() => {
    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  return (
    <div style={{ height: 10000 }}>
      <div style={{ position: "fixed", top: 0, left: 0 }}>
        <p>Debounced top position: {debouncedPosition}</p>
        <p>Real position: {currentPosition}</p>
      </div>
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<Input />, rootElement);
```

**Comment by rtvv** [comment]
I add addEventListener at top component and share window.pageYOffset through contextProvider. 


This way:
```
  const handleScroll = event => {
    setPosition(window.pageYOffset);
  };
```
is visibly lagging :(

**Comment by xnimorz** [comment]
> is visibly lagging :(

Can you create a demo project where we can check what is going wrong?

**Comment by rtvv** [comment]
I don't know how to mesure lag in react. Your code for example https://codesandbox.io/s/10jk10r0m7 is perfectly fine, just add some more nested Components in return and you will see lag. 

Here is chrome Performanse tool:
[Overal](https://i.imgur.com/wuzh2xI.png)
[EventLog](https://i.imgur.com/aIuoS4H.png)
[Warn by chome](https://i.imgur.com/PiFl7Ft.png)

I think every time you setPosition - and it's 50 times in a few second, react rerenders/or scripting to check is there something need to be rerendered. Thats why it's lag.

**Comment by rtvv** [comment]
В общем, скрол вызывает handleScroll раз 30 в секунду судя по консоли и каждый раз мы обрабатываем этот вызов с помощью setPosition(window.pageYOffset). Когда на экране достаточно много компонентов, то прокрутка тормозит заметно.

Смысл в том, чтобы с помощью useDebounce вызывать setPosition или handleScroll не 30 раз в секунду, а 1 раз или и того меньше.

**Comment by xnimorz** [comment]
React hook useDebounce is written for debouncing a state value in a component, but it wasn't created for debouncing event handling. 

It's better to add debouncing into handling function — here is the solution of your use case: https://codesandbox.io/s/32yqlyo815

I also added `updatesCounter` variable to show that component wouldn't get unnecessary updates.

But, yes, your use case is pretty interesting, I'll add such possibility to useDebounce in further versions.
____
Этоа библиотка изначально была сделана, чтобы дебаунсить state элементов, но для дебаунса хендлеров она пока не подходит. 

"Прямо сейчас" — лучше сделать дебаунс в функции-хендлере — здесь я привел как это сделать https://codesandbox.io/s/32yqlyo815 , лишних ререндеров не будет, можно посмотреть как в perfomance вкладке, так и по счетчику обновлений компонентов (я его добавил как `updatesCounter` переменную в примере. 

Кейс довольно интересный, я добавлю такую возможность и для библиотеки, но немногим позже, сейчас будет довольно просто использовать тот workaround, что в примере

**Comment by xnimorz** [comment]
I've just cut the release 0.0.9, which has a new method `useDebouncedCallback`. It allows using debounce for Event Listeners more easily. 

You can find docs and demo here: https://github.com/xnimorz/use-debounce#debounced-callbacks
___

Я выпустил релиз 0.0.9, где добавил новый метод `useDebouncedCallback`. Этот метод позволяет использовать debounce для Event listeners проще. 
Документацию и примеры как реактовских хендлеров, так и нативных событий можно найти здесь https://github.com/xnimorz/use-debounce#debounced-callbacks

**Comment by FoxyWolfy** [comment]
"Simple values debouncing" 
Works great for data entry controls because they're tightly coupled together through the state properties.  Change a property value and 'n' milliseconds later the debounce fires.  The result is the UI stays extreme responsive.

"Debounced callbacks"
Don't use for UI work.   The example callback below will "not fire" until 'n' milliseconds elapse making your UI lagy.
onChange={(e) => debouncedCallback(e.target.value)}
