### ISSUE TITLE
Use deep equality

### ISSUE THREAD

**Issue by dantehemerson** [xnimorz/use-debounce#41]
Could use deep equality to compare objects array in:

https://github.com/xnimorz/use-debounce/blob/f135b40d022afb2e244b2709a78dc1c6262c20b4/src/useDebounce.ts#L4-L6

**Comment by xnimorz** [comment]
Hello @dantehemerson 
You can define your own equality function: 
https://github.com/xnimorz/use-debounce/blob/master/src/useDebounce.ts#L11

So, you can call this hook with custom `equalityFn`

```
// suggest we defined deepEqual somewhere 

const equalityFn = (prev, next) => {
  return deepEqual(prev, next);
};

function MyComponent() {
  const [ state, setState ] = useState({foo: 'bar'});
   const [value] = useDebounce(state, 200, { equalityFn })
}
```

**Comment by dantehemerson** [comment]
It's true,  I had not noticed.
Maybe we could add the list of options to the README?.
If you want, I could help with this.

**Comment by xnimorz** [comment]
We released it several days earlier. I'm going to add list of options to the README during this week.
