### ISSUE TITLE
Return callPending for useDebounced as well?

### ISSUE THREAD

**Issue by Svish** [xnimorz/use-debounce#42]
Wanted to use the `callPending` flag, but now see that it's only returned for `useDebouncedCallback`, not `useDebounced`. Would it be possible to add `callPending` to `useDebounced` as well?

**Comment by xnimorz** [comment]
Hello, @Svish 
Yes, it's possible to add `callPending` to `useDebounced`. 
You are welcome to PR me :)
If not, I'll add it during the 5-7 days.

**Comment by xnimorz** [comment]
Hello again, @Svish .
I've published `useDebounce@3.2.0`  which has `callPending` method for `useDebounce`.

You can find example here: https://github.com/xnimorz/use-debounce/blob/master/test/useDebounce.test.tsx#L276-L302
