### ISSUE TITLE
useDeferredValue

### ISSUE THREAD

**Issue by AjaxSolutions** [xnimorz/use-debounce#43]
This is not an Issue, but I'm posting FYI.

The useDebounce hook is very similar to the experimental React [useDeferredValue](https://reactjs.org/docs/concurrent-mode-reference.html#usedeferredvalue) hook.

However, the useDeferredValue value hook is buggy, and I'd not recommend using it at this time.  One developer wrote that this hook should be renamed to [useDebouncedValue](https://github.com/facebook/react/issues/17185 ).  I agree this would be a better name.

The useDebounce hook is stable and it has more options.

**Comment by xnimorz** [comment]
Thank you, @AjaxSolutions for the info! ❤️
