### ISSUE TITLE
Add engines to package.json

### ISSUE THREAD

**Issue by MichaelDeBoey** [xnimorz/use-debounce#55]

**Comment by xnimorz** [comment]
Hi @MichaelDeBoey 
Thank you for the issue. 
You are welcome to PR me.

**Comment by MichaelDeBoey** [comment]
@xnimorz I couldn't figure out the minimum required Node version, hence the issue

**Comment by xnimorz** [comment]
Hi. It will be node >= 10.0.0
Commit: https://github.com/xnimorz/use-debounce/commit/9d4852cd6657b29b31e8a3bb5657d11f83b650e4
