### ISSUE TITLE
How to restore the behavior of v3 in v4?

### ISSUE THREAD

**Issue by ivan-aksamentov** [xnimorz/use-debounce#63]
How do I preserve the old behavior from version 3? The PR #62 introduced new options, but I tried various combinations of the flags and none gave the old effect. Is this even possible? Maybe the current behavior relies on bugs that I should fix? Am I stuck with v3 now? 

Context:
Just spent 2 hours to pinpoint my new form validation errors to the upgrade of `use-debounce` to version 4.0.0. The funny consequence is that depending on new options' values of `use-debounce`, `yup` (form validation library) either throws errors for all form fields in the form, where messages are just valid field values (probably timing-related), or does not seem to be running at all.

Repro:
I don't have a minimal example, but this is the snippet that breaks in my app:
https://github.com/neherlab/covid19_scenarios/blob/d12969d1cef3c07abb3d54b914c38001aec851e2/src/components/Main/Main.tsx#L119-L153
Reproducible by upgrading "use-debounce" to "4.0.0" and then changing any form value.

cc: @tryggvigy

Thanks for your help!

**Comment by ivan-aksamentov** [comment]
Okay, you just witnessed a rubber duck debugging session. :duck: 


I investigated the 

> throws errors for all form fields in the form

part and found that I should not have returned from the `.then()` part of the snippet above, because `formik` treats the returned things as errors (I returned valid values). So, this was a bug (also, ["thanks" to eslint `promise/always-return` rule that convinced me I should return something](https://github.com/xjamundx/eslint-plugin-promise/issues/59)). It seems that previously the returned thing did not reach `formik`, but now it does somehow.

So the question is: what changed from v3? Did it not return the value before and now it does?

Anyways, this solves it for me, so feel free to close. But I hope this information might help someone else to debug their transition to v4.

**Comment by tryggvigy** [comment]
Hi @ivan-aksamentov! Nice to see you again 😄 hope covid19_scenarios is going well.

> So the question is: what changed in use-debounce from v3? Did it not return the value before and now it does?

Yes, that's right. The new version mimics lodash's implementation of debounce which returns the value.
I'm sorry you had to spend time debugging!

**Comment by xnimorz** [comment]
Hi @ivan-aksamentov 

Yes, now v4 use-debounce returns the value.

**Comment by ivan-aksamentov** [comment]
@tryggvigy, small planet :)

> hope covid19_scenarios is going well

Yep, it's thriving. 6+ months into pandemic, we are now swimming in data. Initial predictions were totally correct too. Not sure if I should be glad or sad about it all. Just released changes for "The Second Wave". Not looking good.


Feel free to close this, folks. Might also add a quick note on the new return behavior to the list of breaking changes, and/or to the readme, in case someone else steps on it.

**Comment by xnimorz** [comment]
I'll add it to the changelog and then I'll close the issue :)

**Comment by xnimorz** [comment]
Added https://github.com/xnimorz/use-debounce/commit/f9f4cb314bb7f17628691ee71e2eecd9174a7a89 :)
