### ISSUE TITLE
npm package is updated to 4.0 but releases page on repo don't reflect possible breaking changes

### ISSUE THREAD

**Issue by RwwL** [xnimorz/use-debounce#64]
More a reminder than an issue; sorry if you would have preferred a quick email or tweet.

**Comment by xnimorz** [comment]
Hi @RwwL 
All the information about the changes we store in the changelog file: https://github.com/xnimorz/use-debounce/blob/master/CHANGELOG.md

I think, I'll add a release using github also.

**Comment by RwwL** [comment]
Perfect, thanks, sorry I missed that!
