### ISSUE TITLE
5.0.3 — useDebouncedCallback export issue

### ISSUE THREAD

**Issue by kamranahmedse** [xnimorz/use-debounce#85]
Hey, firstly thank you for your work on the package, appreciate it.

There is an issue in the latest version `5.0.3`, it seems like `useDebouncedCallback` hasn't been exported properly

```shell
ModuleNotFoundError: Module not found: Error: Package path ./lib/useDebouncedCallback is not exported from package /node_modules/use-debounce (see exports field in /node_modules/use-debounce/package.json)
```

**Comment by xnimorz** [comment]
Hi @kamranahmedse !
Could you provide your import line with useDebounce, please?

**Comment by kamranahmedse** [comment]
It is [as per the docs](https://github.com/xnimorz/use-debounce#debounced-callbacks)

```typescript
import { useDebouncedCallback } from 'use-debounce';
```

**Comment by xnimorz** [comment]
I've tried to reproduce the problem, but it worked. 

Could you provide a small example of the described problem?

**Comment by kamranahmedse** [comment]
Ah, my bad, one of the "hidden" imports in the project was wrong.

```diff
- import useDebouncedCallback from 'use-debounce/lib/useDebouncedCallback';
+ import { useDebouncedCallback } from 'use-debounce';
```

Apologies for the hassle. Thank you Nik! :)

**Comment by bertho-zero** [comment]
I have this issue with the latest `use-debounce` and only one import like:

```js
import { useDebouncedCallback } from 'use-debounce';
```

```
Module not found: Error: Package path . is not exported from package /home/bertho/dev/oa/node_modules/use-debounce (see exports field in /home/bertho/dev/oa/node_modules/use-debounce/package.json)
```

**Comment by bertho-zero** [comment]
I found right after writing the comment, if you modify `conditionNames` in your webpack config, consider adding `...`:

```diff
- conditionNames: ['oa']
+ conditionNames: ['oa', '...']
```

**Comment by benjgil** [comment]
was banging my head against a wall for days on this
thanks!
