### ISSUE TITLE
Changelog for 5.0.4?

### ISSUE THREAD

**Issue by bengtan** [xnimorz/use-debounce#88]
Hi,

5.0.4 was published to npmjs.com five days ago. Are there are release notes/changelogs for it?

**Comment by xnimorz** [comment]
Hi @bengtan 
I was interrupted, so I forgot to push these changes, thank you. 
5.0.4 adds correct export maps for React Native (https://github.com/xnimorz/use-debounce/issues/86)

**Comment by xnimorz** [comment]
published
